CREATE DATABASE projetoEcommerce;

use projetoEcommerce;


CREATE TABLE cliente (
  idCliente INT UNSIGNED  AUTO_INCREMENT PRIMARY KEY,
  CPF VARCHAR(11)  NULL,
  CNPJ VARCHAR(15)  NULL,
  Nome VARCHAR(45) NULL,
  Razão_Social VARCHAR(45) NULL,
  CEP VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  Telefone VARCHAR(45) NOT NULL,
  CONSTRAINT unique_CPF UNIQUE(CPF),
  CONSTRAINT unique_CNPJ UNIQUE(CNPJ)
  );
  
CREATE TABLE produto(
  idProduto INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Categoria ENUM('ELETRONICOS','VESTIMENTAS','BRINQUEDOS', 'ALIMENTOS', 'MOVEIS') NOT NULL
  );
  

  CREATE TABLE pedido(
  idPedido INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  StatusPedido ENUM('CANCELADO', 'CONFIRMADO', 'EM PROCESSAMENTO') DEFAULT 'EM PROCESSAMENTO',
  Cliente_idCliente INT UNSIGNED NOT NULL,  
  CONSTRAINT fk_Cliente_idCliente FOREIGN KEY (Cliente_idCliente) REFERENCES cliente(idCliente)
    );
    
CREATE TABLE pagamento(
	idPagamento INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TipoPagamento enum('PIX','BOLETO', 'CARTÃO', 'DEPOSITO','CHEQUE'),
    Valor FLOAT DEFAULT 0.0,
	Pagamento BOOLEAN DEFAULT FALSE,
    Pedido_idPedido INT UNSIGNED NOT NULL,
    CONSTRAINT  fk_Pedido_idPedido FOREIGN KEY (Pedido_idPedido) REFERENCES pedido(idPedido)
);

CREATE TABLE estoque(
  idEstoque INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CEP VARCHAR(45) NULL,
  Telefone VARCHAR(15) NULL,
  Email VARCHAR(20) NULL,
  Quantidade INT UNSIGNED DEFAULT 0
 );
 
 
  